# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(default='未记录', max_length=16)),
                ('grade', models.IntegerField(default=0, verbose_name=2048)),
                ('sum', models.IntegerField(default=0, verbose_name=128)),
            ],
            options={
                'db_table': 'TWSS_Class',
            },
        ),
        migrations.CreateModel(
            name='PraticeClass',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='未记录', max_length=32)),
                ('year', models.IntegerField(default=0, verbose_name=2048)),
                ('semester', models.IntegerField(default=0, verbose_name=2)),
                ('period', models.IntegerField(default=0, verbose_name=128)),
                ('credit', models.IntegerField(default=0, verbose_name=16)),
                ('attribute', models.CharField(default='未记录', max_length=4)),
                ('audit_status', models.CharField(default='未记录', max_length=4)),
            ],
            options={
                'db_table': 'TWSS_PraticeClass',
            },
        ),
        migrations.CreateModel(
            name='TheoryClass',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='未记录', max_length=32)),
                ('year', models.IntegerField(default=0, verbose_name=2048)),
                ('semester', models.IntegerField(default=0, verbose_name=2)),
                ('period', models.IntegerField(default=0, verbose_name=128)),
                ('credit', models.IntegerField(default=0, verbose_name=16)),
                ('attribute', models.CharField(default='未记录', max_length=4)),
                ('audit_status', models.CharField(default='未记录', max_length=4)),
            ],
            options={
                'db_table': 'TWSS_TheoryClass',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='未记录', max_length=16)),
                ('title', models.CharField(default='未记录', max_length=16)),
                ('department', models.CharField(default='未记录', max_length=8)),
                ('status', models.CharField(default='未记录', max_length=16)),
                ('password', models.CharField(default='未记录', max_length=32)),
                ('phone_number', models.CharField(default='未记录', max_length=11)),
                ('email', models.CharField(default='未记录', max_length=32)),
            ],
            options={
                'db_table': 'TWSS_User',
            },
        ),
        migrations.AddField(
            model_name='theoryclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.User'),
        ),
        migrations.AddField(
            model_name='praticeclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.User'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.User'),
        ),
    ]
