# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未记录', max_length=128)),
                ('author', models.CharField(default='未记录', max_length=16)),
                ('publish', models.CharField(default='未记录', max_length=128)),
                ('award', models.CharField(default='未记录', max_length=256)),
                ('audit_status', models.CharField(default='未记录', max_length=4)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.User')),
            ],
            options={
                'db_table': 'TWSS_TeachingAchievement',
            },
        ),
        migrations.CreateModel(
            name='TeachingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未记录', max_length=128)),
                ('author', models.CharField(default='未记录', max_length=16)),
                ('publish', models.CharField(default='未记录', max_length=128)),
                ('award', models.CharField(default='未记录', max_length=256)),
                ('audit_status', models.CharField(default='未记录', max_length=4)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.User')),
            ],
            options={
                'db_table': 'TWSS_TeachingProject',
            },
        ),
        migrations.RenameModel(
            old_name='PraticeClass',
            new_name='PraticeCourse',
        ),
        migrations.RenameModel(
            old_name='TheoryClass',
            new_name='TheoryCourse',
        ),
        migrations.AlterModelTable(
            name='praticecourse',
            table='TWSS_PraticeCourse',
        ),
        migrations.AlterModelTable(
            name='theorycourse',
            table='TWSS_TheoryCourse',
        ),
    ]
