# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
