# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170819_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praticecourse',
            name='year',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='theorycourse',
            name='year',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
