# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20170820_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingachievement',
            name='type',
            field=models.CharField(default='未记录', max_length=16),
        ),
        migrations.AddField(
            model_name='teachingproject',
            name='type',
            field=models.CharField(default='未记录', max_length=16),
        ),
    ]
