# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170824_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praticecourse',
            name='attribute',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='praticecourse',
            name='audit_status',
            field=models.BooleanField(default=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='praticecourse',
            name='credit',
            field=models.IntegerField(default=0, verbose_name=8),
        ),
        migrations.AlterField(
            model_name='praticecourse',
            name='year',
            field=models.IntegerField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='theorycourse',
            name='attribute',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='theorycourse',
            name='audit_status',
            field=models.BooleanField(default=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='theorycourse',
            name='credit',
            field=models.IntegerField(default=0, verbose_name=8),
        ),
        migrations.AlterField(
            model_name='theorycourse',
            name='year',
            field=models.IntegerField(default=0, max_length=12),
        ),
    ]
